### ISSUE TITLE
Meteor 1.6 and node version

### ISSUE THREAD

**Issue by snajjar** [zodern/mup-aws-beanstalk#17] opened 2018-01-24 23:16 UTC
First of all, thanks for the awesome plugin!

It seems that by default, it won't deploy Meteor 1.6 with the right node version (8). EC2 instances are installed with node 6.

I managed to solved the issue with the following configuration:

    customBeanstalkConfig: [
        {
            namespace: 'aws:elasticbeanstalk:container:nodejs',
            option: 'NodeVersion',
            value: '8.9.3'
        }
    ]

But still, I believe there should be a direct option to let the user configure the node version. The plugin could just read the node version from the mup.js file and add the above configuration the the beanstalk config.

What do you think?

**Comment by zodern** [comment] 2018-02-01 23:16
The app actually doesn't use the node version in the beanstalk configuration. It uses a separate version [managed by nvm](https://github.com/zodern/mup-aws-beanstalk/blob/master/src/assets/node.yaml). Other people have been confused by this too, so the docs should be updated to make this more clear.

It always uses the node version [Meteor says to use in the bundle](https://github.com/zodern/mup-aws-beanstalk/blob/master/src/utils.js#L115). 

What is the reason you want to choose the node version?

**Comment by resmith** [comment] 2018-02-22 14:56
Got the same issue when deploying a Meteor 1.6 app:

=> Starting health check server
=> Starting App
Meteor requires Node v8.0.0 or later.

npm ERR! Linux 4.9.76-3.78.amzn1.x86_64
npm ERR! argv "/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin/npm" "start"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! mup-rlives@1.0.0 start: `bash ./start.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mup-rlives@1.0.0 start script 'bash ./start.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mup-rlives package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bash ./start.sh

**Comment by zodern** [comment] 2018-02-22 15:35
@resmith in the aws console, go to the beanstalk app, click logs, and request the full logs. In the zip file you download, there will be an `eb-activity.log` file. Please paste here the output from that file between the lines containing `StartupStage0/AppDeployPreHook/49node.sh] : Starting activity...` and `StartupStage0/AppDeployPreHook/50npm.sh] : Starting activity...`.

**Comment by resmith** [comment] 2018-02-22 18:54
Strange. I see it saying its using the latest version of Node, but when I do 'mup logs' I get the error above.

Thanks for your help on this and let me know what else you need.


[2018-02-22T18:45:42.933Z] INFO  [3059]  - [Application deployment 1@1/StartupStage0/AppDeployPreHook/49node.sh] : Starting activity...
[2018-02-22T18:45:54.879Z] INFO  [3059]  - [Application deployment 1@1/StartupStage0/AppDeployPreHook/49node.sh] : Completed activity. Result:
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 12492  100 12492    0     0  83991      0 --:--:-- --:--:-- --:--:-- 84405
  => Downloading nvm from git to '/.nvm'
  
=> Cloning into '/.nvm'...
  Note: checking out 'b546436113084d6de584c57b259b947dd467a900'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by performing another checkout.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -b with the checkout command again. Example:
  
    git checkout -b <new-branch-name>
  
  => Compressing and cleaning up git repository
  
  => Profile not found. Tried ~/.bashrc, ~/.bash_profile, ~/.zshrc, and ~/.profile.
  => Create one of them and run this script again
     OR
  => Append the following lines to the correct file yourself:
  
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  => Close and reopen your terminal to start using nvm or run the following to use it now:
  
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  Downloading and installing node v8.9.4...
  Downloading https://nodejs.org/dist/v8.9.4/node-v8.9.4-linux-x64.tar.xz...
  
#                                                                          1.9%
######################################                                    53.0%
######################################################################## 100.0%
  Computing checksum with sha256sum
  Checksums matched!
  Now using node v8.9.4 (npm v5.6.0)
  Creating default alias: [0;32mdefault[0m [0;90m->[0m [0;32m8.9.4[0m ([0;90m->[0m [0;32mv8.9.4[0m)
  Now using node v8.9.4 (npm v5.6.0)
  [0;32mdefault[0m [0;90m->[0m [0;32m8.9.4[0m ([0;90m->[0m [0;32mv8.9.4[0m)
  /.nvm/versions/node/v8.9.4/bin/npm -> /.nvm/versions/node/v8.9.4/lib/node_modules/npm/bin/npm-cli.js
  /.nvm/versions/node/v8.9.4/bin/npx -> /.nvm/versions/node/v8.9.4/lib/node_modules/npm/bin/npx-cli.js
  + npm@5.6.0
  updated 2 packages in 7.381s
[2018-02-22T18:45:54.880Z] INFO  [3059]  - [Application deployment 1@1/StartupStage0/AppDeployPreHook/50npm.sh] : Starting activity...
[2018-02-22T18:46:10.623Z] INFO  [3059]  - [Application deployment 1@1/StartupStage0/AppDeployPreHook/50npm.sh] : Completed activity. Result:

**Comment by resmith** [comment] 2018-02-23 14:20
Zodern wrote up above: The app actually doesn't use the node version in the beanstalk configuration. It uses a separate version managed by nvm. Other people have been confused by this too, so the docs should be updated to make this more clear.

It always uses the node version Meteor says to use in the bundle.

**Comment by zodern** [comment] 2018-02-23 17:55
I have found a bug causing it to not use the version installed by nvm. I am looking into the cause.

**Comment by resmith** [comment] 2018-02-23 17:57
That's great news. Thanks for looking into it.

**Comment by resmith** [comment] 2018-03-03 16:31
Zodern, would it not be better not to use NVM in the docker container in order to make the docker container as small as possible?

**Comment by zodern** [comment] 2018-03-04 03:27
@resmith I am unaware of any api to find the available node versions aws beanstalk can install (it is constantly changing, and the available versions is limited).

This is fixed in 0.5.0. You can update with `npm i -g mup-aws-beanstalk`.

**Closed by zodern** 2018-03-04 03:27 UTC
Labels: bug
